# This file is a template, and might need editing before it works on your project.
# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages
#
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: "$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS"
      when: never
    - if: "$CI_COMMIT_BRANCH"

variables:
  EB_IMAGE_TAG: $CI_REGISTRY_IMAGE/elasticbeanstalk:latest

stages:
  - build
  - staging
  - test
  - production

format:
  stage: build
  image: python:3.7.10-slim
  before_script: pip install black
  script: black --check gavel

lint:
  stage: build
  image: python:3.7.10-slim
  before_script: pip install pylint
  script: pylint gavel
  allow_failure: true

build_eb_image:
  stage: build
  image: docker:20.10.10
  rules:
    - if: '$CI_COMMIT_BRANCH == "mainline"'
      changes:
        - eb.Dockerfile
        - .dockerignore
  services:
    - docker:20.10.10-dind
  tags:
    - gitlab-org-docker
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $EB_IMAGE_TAG - < eb.Dockerfile
    - docker push $EB_IMAGE_TAG

prod_stop:
  stage: production
  image: $EB_IMAGE_TAG
  rules:
    - if: '$CI_COMMIT_BRANCH == "mainline"'
  environment:
    name: prod
    url: judging.hacktx.com
    action: stop
  retry: 1
  before_script:
    - mkdir ~/.aws/
    - touch ~/.aws/credentials
    - 'printf "[eb-cli]\naws_access_key_id = %s\naws_secret_access_key = %s\n" "$AWS_ACCESS_KEY_ID" "$AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials'
    - ls -al ~/.aws
    - eb init freetail-gavel -p "Python 3.7"
  script: eb terminate gavel-prod

prod_deploy:
  extends: prod_stop
  needs: ["prod_stop"]
  environment:
    name: prod
    url: judging.hacktx.com
    action: start
  script:
    - mv $CI_ENV_FILE_PROD .env
    - eb create gavel-prod -d -c gavel -it t2.micro,t3.micro -im 1 -ix 4 --scale 1 -db.engine postgres -db.i db.t3.micro -db.size 5 -db.user postgres -db.pass $DB_PASSWORD_PROD -db.version 14.2
